version: '3.9'
services:
  api:
    build:
      context: ..
      dockerfile: api/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ..
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
  worker-scan:
    build:
      context: ..
      dockerfile: workers/scan/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: virus
      POSTGRES_PASSWORD: virus
      POSTGRES_DB: virus
    ports:
      - "5432:5432"
  opensearch:
    image: opensearchproject/opensearch:2.12.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin123
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
